### ISSUE TITLE
Error in Inference step

### ISSUE THREAD

**Issue by ypjoshi18** [physical-superintelligence-lab/Agent-Driver#11]
Hi, I am running AgentDriver code. But getting below error in evaluation step.
I am getting below errors for following commands.
1. sh scripts/run_inference.sh 
error - Streaming output truncated to the last 5000 lines.
Invalid token: e3dbf6e92f0e4ac3860f1cbf73e2a312
An error occurred: [Errno 2] No such file or directory: 'data/val/2dc6dfa0bf9441f6a2397e7d4ec424ad.pkl'
Invalid token: 2dc6dfa0bf9441f6a2397e7d4ec424ad
An error occurred: [Errno 2] No such file or directory: 'data/val/e6d1a6c5413942bdaa26ce0c0e5330ad.pkl'
Invalid token: e6d1a6c5413942bdaa26ce0c0e5330ad
An error occurred: [Errno 2] No such file or directory: 'data/val/b421615151244708b1efe89c5147eaaf.pkl'
Invalid token: b421615151244708b1efe89c5147eaaf

2. sh scripts/run_evaluation.sh uniad YOUR_PRED_DICT_PATH

error - 2024-11-12 06:23:56.069425: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-12 06:23:56.113573: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-12 06:23:56.127206: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-12 06:23:56.178478: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-12 06:23:58.263757: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/Agent-Driver/agentdriver/evaluation/evaluation.py", line 116, in <module>
    planning_evaluation(pred_trajs_dict, config)
  File "/content/Agent-Driver/agentdriver/evaluation/evaluation.py", line 20, in planning_evaluation
    with open(Path(os.path.join(config.gt_folder, 'uniad_gt_seg.pkl')),'rb') as f:
AttributeError: 'Namespace' object has no attribute 'gt_folder'

**Comment by ShaohuaDong2021** [comment]
Same error

**Comment by ShaohuaDong2021** [comment]
Change the parser.add_argument('--gt_dir') to parser.add_argument('--gt_folder')

**Comment by ShaohuaDong2021** [comment]
Modify the argument definition from parser.add_argument('--gt_dir') to parser.add_argument('--gt_folder').
